services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    
    # Healthcheck to verify service is ready
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/ping"]
      start_period: 5s
      interval: 10s
      timeout: 3s
      retries: 3
    
    networks:
      - traefik-public
    
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    
    environment:
      - TZ=${TZ:-UTC}
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic:/etc/traefik/dynamic:ro
      - ./logs:/var/log/traefik
      - ./certs:/etc/traefik/certs
    
    labels:
      - "traefik.enable=true"
    
    # Config file is set in dev/prod overrides via 'command'
    command:
      - "--configFile=/etc/traefik/traefik.yml"

networks:
  traefik-public:
    name: ${TRAEFIK_NETWORK:-traefik-public}
    external: true