services:
  traefik:
    # ==========================================
    # PUERTOS - Solo accesibles desde localhost
    # ==========================================
    # CRÍTICO SEGURIDAD: En desarrollo, exponer solo a localhost
    # Evita que personas en la red accedan al dashboard sin autenticación
    ports:
      # Dashboard: Solo localhost (puerto 8080)
      - "127.0.0.1:8080:8080"
      # HTTP: Accessible desde cualquier interfaz (desarrollo necesita acceso)
      - "80:80"
      # HTTPS: Accessible desde cualquier interfaz
      - "443:443"
    
    # Añade volúmenes específicos de desarrollo
    volumes:
      # Configuración estática de desarrollo
      - ./config/traefik.dev.yml:/etc/traefik/traefik.dev.yml:ro
      
      # Configuración dinámica compartida (tls, routers, middlewares base)
      - ./config/dynamic:/etc/traefik/dynamic:ro
      
      # Logs específicos de desarrollo
      - ./logs/dev:/var/log/traefik/dev
      
      # Certificados autofirmados para desarrollo
      - ./certs/dev:/etc/traefik/certs/dev:ro
    
    # Variables de entorno específicas de desarrollo
    environment:
      - ENVIRONMENT=dev
      - TRAEFIK_LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    
    # Labels adicionales para desarrollo
    labels:
      # Dashboard sin autenticación en desarrollo (solo localhost)
      - "traefik.http.routers.dashboard.middlewares="
      
      # Habilitar API en modo inseguro (solo para desarrollo)
      - "traefik.http.routers.api.rule=Host(`traefik.${DEV_DOMAIN:-localhost}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web"
    
    # Comando para usar la configuración de desarrollo
    command:
      - "--configFile=/etc/traefik/traefik.dev.yml"