# ==========================================
# DEFINICIONES REUTILIZABLES (YAML Anchors)
# ==========================================
x-traefik-common: &traefik-common
  image: traefik:v3.5
  container_name: traefik
  restart: unless-stopped
  security_opt:
    - no-new-privileges:true
  healthcheck:
    test: ["CMD", "traefik", "healthcheck", "--ping"]
    start_period: 5s
    interval: 10s
    timeout: 3s
    retries: 3
  networks:
    - traefik-public
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.dashboard.rule=Host(`traefik.${DEV_DOMAIN:-localhost}`)"
    - "traefik.http.routers.dashboard.service=api@internal"
    - "traefik.http.routers.dashboard.entrypoints=web"

# Volúmenes base (comunes en dev y prod)
x-traefik-volumes: &traefik-volumes
  - /var/run/docker.sock:/var/run/docker.sock:ro
  - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
  - ./config/dynamic:/etc/traefik/dynamic:ro
  - ./logs:/var/log/traefik
  - ./certs:/etc/traefik/certs

# Variables de entorno base
x-traefik-env: &traefik-env
  TZ: ${TZ:-UTC}
  TRAEFIK_API_INSECURE: "false"
  TRAEFIK_METRICS_PROMETHEUS: "true"

services:
  traefik:
    <<: *traefik-common
    
    # ==========================================
    # PUERTOS (modificables por override)
    # ==========================================
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
      - "${DASHBOARD_PORT:-8080}:8080"
    
    # ==========================================
    # VARIABLES DE ENTORNO BASE
    # ==========================================
    environment:
      <<: *traefik-env
    
    # ==========================================
    # VOLÚMENES BASE (modificables por override)
    # ==========================================
    volumes: *traefik-volumes

# ==========================================
# RED EXTERNA
# ==========================================
# Compartida por todos los servicios/ambientes
networks:
  traefik-public:
    name: ${TRAEFIK_NETWORK:-traefik-public}
    external: true