services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: unless-stopped
    
    # Permisos necesarios para que Traefik escuche en puertos privilegiados
    security_opt:
      - no-new-privileges:true
    
    # Puertos expuestos
    ports:
      - "${HTTP_PORT:-80}:80"       # HTTP
      - "${HTTPS_PORT:-443}:443"     # HTTPS
      - "${DASHBOARD_PORT:-8080}:8080"  # Dashboard (solo para desarrollo/localhost)
    
    # Variables de entorno
    environment:
      - TZ=${TZ:-UTC}
    
    # ==========================================
    # HEALTH CHECK - CRITICAL PARA PRODUCTION
    # ==========================================
    # Monitorea que Traefik realmente está funcionando
    # Si falla, Docker puede reiniciar el contenedor automáticamente
    healthcheck:
      # Verificar que Traefik responde en puerto 8080 (API)
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      # Esperar 5 segundos antes de hacer first check
      start_period: 5s
      # Intervalo entre health checks
      interval: 10s
      # Timeout máximo para el comando
      timeout: 3s
      # Número de fallos consecutivos para marcar como unhealthy
      retries: 3
    
    # Volúmenes compartidos entre dev y prod
    volumes:
      # Socket de Docker para detectar contenedores automáticamente
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
      # Configuración estática (se carga al iniciar)
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      
      # Configuración dinámica (se recarga automáticamente)
      - ./config/dynamic:/etc/traefik/dynamic:ro
      
      # Logs
      - ./logs:/var/log/traefik
      
      # Certificados
      - ./certs:/etc/traefik/certs
    
    # Redes
    networks:
      - traefik-public
    
    # Labels para el dashboard
    labels:
      - "traefik.enable=true"
      
      # Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DEV_DOMAIN:-localhost}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"

# Red externa que compartirán todos los proyectos
networks:
  traefik-public:
    name: ${TRAEFIK_NETWORK:-traefik-public}
    external: true