services:
  traefik:
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic:/etc/traefik/dynamic:ro
      - ./logs:/var/log/traefik
      - ./certs:/etc/traefik/certs
      
      - ./config/traefik.prod.yml:/etc/traefik/traefik.prod.yml:ro
      - ./config/dynamic/prod:/etc/traefik/dynamic/prod:ro
      - ./logs/prod:/var/log/traefik/prod
      
      - ./certs/prod:/etc/traefik/certs/prod

    networks:
      - traefik-public
      - traefik-proxy
    
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
        labels: "service=traefik,env=prod"
    
    environment:
      - TZ=${TZ:-UTC}
      - TRAEFIK_API_INSECURE=false
      - ENVIRONMENT=prod
      - TRAEFIK_LOG_LEVEL=${LOG_LEVEL:-WARN}
      
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:?Error: LETSENCRYPT_EMAIL no está definido en .env}
      - PROD_DOMAIN=${PROD_DOMAIN:?Error: PROD_DOMAIN no está definido en .env}
      
      - PROD_CORS_ORIGINS=${PROD_CORS_ORIGINS:-}
    
    labels:
      - "com.traefik.environment=prod"
      
      - "traefik.enable=true"
      
      - "traefik.http.middlewares.prod-cors-dynamic.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,PATCH,OPTIONS"
      - "traefik.http.middlewares.prod-cors-dynamic.headers.accessControlAllowOriginList=https://${PROD_DOMAIN},https://www.${PROD_DOMAIN}${PROD_CORS_ORIGINS:+,${PROD_CORS_ORIGINS}}"
      - "traefik.http.middlewares.prod-cors-dynamic.headers.accessControlAllowHeaders=Content-Type,Authorization,X-Requested-With"
      - "traefik.http.middlewares.prod-cors-dynamic.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.prod-cors-dynamic.headers.accessControlMaxAge=3600"
      - "traefik.http.middlewares.prod-cors-dynamic.headers.addVaryHeader=true"
      
      - "traefik.http.routers.dashboard-secure.rule=Host(`traefik.${PROD_DOMAIN}`)"
      - "traefik.http.routers.dashboard-secure.service=api@internal"
      - "traefik.http.routers.dashboard-secure.entrypoints=websecure"
      - "traefik.http.routers.dashboard-secure.tls=true"
      - "traefik.http.routers.dashboard-secure.tls.certresolver=letsencrypt"

      - "traefik.http.routers.dashboard-secure.middlewares=dashboard-ipwhitelist,dashboard-ratelimit,dashboard-auth,dashboard-security"
      
      - "traefik.http.middlewares.dashboard-ipwhitelist.ipwhitelist.sourcerange=${DASHBOARD_ALLOWED_IPS:-127.0.0.1/32}"
      
      - "traefik.http.middlewares.dashboard-ratelimit.ratelimit.average=5"
      - "traefik.http.middlewares.dashboard-ratelimit.ratelimit.burst=10"
      - "traefik.http.middlewares.dashboard-ratelimit.ratelimit.period=1s"
      
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_USER}:${TRAEFIK_DASHBOARD_PASSWORD}"
      
      - "traefik.http.middlewares.dashboard-security.headers.customFrameOptionsValue=DENY"
      - "traefik.http.middlewares.dashboard-security.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.dashboard-security.headers.customResponseHeaders.X-XSS-Protection=1; mode=block"
      - "traefik.http.middlewares.dashboard-security.headers.customResponseHeaders.Strict-Transport-Security=max-age=31536000; includeSubDomains"
      
      - "traefik.http.routers.dashboard-http.rule=Host(`traefik.${PROD_DOMAIN}`)"
      - "traefik.http.routers.dashboard-http.entrypoints=web"
      - "traefik.http.routers.dashboard-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    
    command:
      - "--configFile=/etc/traefik/traefik.prod.yml"

networks:
  traefik-public:
    external: true
  
  traefik-proxy:
    external: true
    name: traefik-proxy
