services:
  traefik:
    # Dev ports: Dashboard accessible without TLS on localhost:8080
    ports:
      - "127.0.0.1:8080:8080"
      - "80:80"
      - "443:443"
    
    volumes:
      - ./config/traefik.dev.yml:/etc/traefik/traefik.dev.yml:ro
      - ./config/dynamic/dev:/etc/traefik/dynamic/dev:ro
      - ./certs/dev:/etc/traefik/certs/dev:ro
    
    environment:
      - TRAEFIK_API_INSECURE=true
      - TRAEFIK_LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DEV_DOMAIN:-localhost}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
    
    command:
      - "--configFile=/etc/traefik/traefik.dev.yml"
