services:
  traefik:
    volumes:
      - ./config/traefik.prod.yml:/etc/traefik/traefik.prod.yml:ro
      - ./config/dynamic/prod:/etc/traefik/dynamic/prod:ro
      - ./certs/prod:/etc/traefik/certs/prod:ro
      - ./logs/prod:/var/log/traefik
    
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
        labels: "service=traefik,env=prod"
    
    environment:
      - TRAEFIK_API_INSECURE=false
      - TRAEFIK_LOG_LEVEL=${LOG_LEVEL:-WARN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - PROD_DOMAIN=${PROD_DOMAIN}
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-secure.rule=Host(`traefik.${PROD_DOMAIN}`)"
      - "traefik.http.routers.dashboard-secure.service=api@internal"
      - "traefik.http.routers.dashboard-secure.entrypoints=websecure"
      - "traefik.http.routers.dashboard-secure.tls=true"
      - "traefik.http.routers.dashboard-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard-secure.middlewares=dashboard-auth,dashboard-security"
      
      # Basic auth for dashboard
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_USER}:${TRAEFIK_DASHBOARD_PASSWORD}"
      
      # Security headers for dashboard
      - "traefik.http.middlewares.dashboard-security.headers.customFrameOptionsValue=DENY"
      - "traefik.http.middlewares.dashboard-security.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.dashboard-security.headers.customResponseHeaders.Strict-Transport-Security=max-age=31536000; includeSubDomains"
      
      # HTTP to HTTPS redirect
      - "traefik.http.routers.dashboard-http.rule=Host(`traefik.${PROD_DOMAIN}`)"
      - "traefik.http.routers.dashboard-http.entrypoints=web"
      - "traefik.http.routers.dashboard-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    
    command:
      - "--configFile=/etc/traefik/traefik.prod.yml"