services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:0.1.1
    container_name: traefik-socket-proxy
    restart: unless-stopped
    
    security_opt:
      - no-new-privileges:true
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    networks:
      - traefik-proxy
    
    ports:
      - "127.0.0.1:2375:2375"
    
    environment:
      CONTAINERS: 1
      SERVICES: 1
      NETWORKS: 1
      EVENTS: 1
      
      VOLUMES: 0
      IMAGES: 0
      BUILD: 0
      COMMIT: 0
      CONFIGS: 0
      SECRETS: 0
      DISTRIBUTION: 0
      NODES: 0
      PLUGINS: 0
      TASKS: 0
      EXEC: 0
      
      POST: 0      
      PUT: 0              
      DELETE: 0          
      
      INFO: 0
      SYSTEM: 0

networks:
  traefik-proxy:
    name: traefik-proxy
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
