# Production TLS configuration
# Let's Encrypt certificates are managed by the certificatesResolvers in traefik.prod.yml
# This file configures TLS options and cipher suites

tls:
  options:
    default:
      minVersion: "VersionTLS12"
      sniStrict: true
      alpnProtocols:
        - "h2"
        - "http/1.1"

    modern:
      minVersion: "VersionTLS13"
      sniStrict: true
      alpnProtocols:
        - "h2"
        - "http/1.1"