http:
  middlewares:
    prod-security:
      headers:
        frameDeny: true
        customFrameOptionsValue: "SAMEORIGIN"
        
        sslRedirect: true
        sslForceHost: true
        
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        
        referrerPolicy: "strict-origin-when-cross-origin"
        
        permissionsPolicy: "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
        
        contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'"

    prod-cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        accessControlAllowOriginList:
          - "https://example.com"
          - "https://www.example.com"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-Requested-With"
        accessControlAllowCredentials: true
        accessControlMaxAge: 3600
        addVaryHeader: true
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-Requested-With"
        accessControlAllowCredentials: true
        accessControlMaxAge: 3600
        addVaryHeader: true