# Development TLS configuration with self-signed certificates

tls:
  certificates:
    - certFile: "/etc/traefik/certs/dev/localhost.crt"
      keyFile: "/etc/traefik/certs/dev/localhost.key"
      stores:
        - default

  options:
    default:
      minVersion: "VersionTLS12"
      sniStrict: false
      alpnProtocols:
        - "h2"
        - "http/1.1"

  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certs/dev/localhost.crt"
        keyFile: "/etc/traefik/certs/dev/localhost.key"