# Development-specific middlewares for relaxed security and CORS

http:
  middlewares:
    # ============================================================================
    # CORS - Allow all origins (convenient for local development)
    # ============================================================================
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        accessControlAllowOriginList:
          - "*"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-Requested-With"
        accessControlAllowCredentials: false
        accessControlMaxAge: 3600
        addVaryHeader: true

    # ============================================================================
    # DEBUG HEADERS - Mark responses as coming from dev
    # ============================================================================
    debug-headers:
      headers:
        customResponseHeaders:
          X-Debug-Environment: "development"
          X-Debug-Server: "traefik-dev"

    # ============================================================================
    # RELAXED SECURITY - No HTTPS enforcement in dev (use on specific routes only)
    # ============================================================================
    relaxed-security:
      headers:
        frameDeny: false
        contentTypeNosniff: true
        browserXssFilter: true
        sslRedirect: false
        referrerPolicy: "strict-origin-when-cross-origin"