http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "geolocation=(), microphone=(), camera=()"
        customFrameOptionsValue: "SAMEORIGIN"

    cors-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        accessControlAllowOriginList:
          - "*"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-Requested-With"
        accessControlMaxAge: 100
        addVaryHeader: true

    rate-limit:
      rateLimit:
        average: 30
        burst: 60
        period: 1s

    rate-limit-strict:
      rateLimit:
        average: 10
        burst: 20
        period: 1s

    rate-limit-public:
      rateLimit:
        average: 5
        burst: 10
        period: 1s
        sourceCriterion:
          ipStrategy:
            depth: 1

    rate-limit-internal:
      rateLimit:
        average: 50
        burst: 100
        period: 1s

    compression:
      compress:
        excludedContentTypes:
          - "text/event-stream"

    retry:
      retry:
        attempts: 3
        initialInterval: 100ms

    redirect-non-www:
      redirectRegex:
        regex: "^https://www\\.(.+)"
        replacement: "https://${1}"
        permanent: true

    auth-basic:
      basicAuth:
        users:
          - "admin:$apr1$..."

    ip-whitelist-local:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
          - "192.168.0.0/16"
          - "10.0.0.0/8"
          - "172.16.0.0/12"

    api-headers:
      headers:
        customResponseHeaders:
          X-Custom-Response-Header: "value"
        customRequestHeaders:
          X-Custom-Request-Header: "value"

    buffering:
      buffering:
        maxRequestBodyBytes: 10485760
        memRequestBodyBytes: 2097152
        maxResponseBodyBytes: 10485760
        memResponseBodyBytes: 2097152
        retryExpression: "IsNetworkError() && Attempts() < 2"