http:
  middlewares:
    # ============================================================================
    # SECURITY HEADERS
    # ============================================================================
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "geolocation=(), microphone=(), camera=()"

    # ============================================================================
    # RATE LIMITING
    # ============================================================================
    rate-limit:
      rateLimit:
        average: 30
        burst: 60
        period: 1s

    rate-limit-strict:
      rateLimit:
        average: 10
        burst: 20
        period: 1s

    # ============================================================================
    # COMPRESSION
    # ============================================================================
    compression:
      compress:
        excludedContentTypes:
          - "text/event-stream"

    # ============================================================================
    # RETRIES
    # ============================================================================
    retry:
      retry:
        attempts: 3
        initialInterval: 100ms

    # ============================================================================
    # REDIRECTIONS
    # ============================================================================
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    redirect-non-www:
      redirectRegex:
        regex: "^https://www\\.(.+)"
        replacement: "https://${1}"
        permanent: true

    # ============================================================================
    # IP FILTERING
    # ============================================================================
    ip-whitelist-local:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
          - "192.168.0.0/16"
          - "10.0.0.0/8"
          - "172.16.0.0/12"