# Routers can be defined here (file provider) or via Docker container labels (recommended)
# This file is kept for reference and future shared route configurations

http:
  routers: {}
  services: {}
  middlewares: {}