tls:
  options:
    default:
      minVersion: "VersionTLS12"
      alpnProtocols:
        - "h2"
        - "http/1.1"

    modern:
      minVersion: "VersionTLS13"
      alpnProtocols:
        - "h2"
        - "http/1.1"