# Production-specific Traefik configuration

global:
  sendAnonymousUsage: false

# HTTP redirects to HTTPS
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: "letsencrypt"

# Extend providers from base
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik-public"
    watch: true

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Let's Encrypt certificate resolver
certificatesResolvers:
  letsencrypt:
    acme:
      email: "{{ env \"LETSENCRYPT_EMAIL\" }}"
      storage: "/etc/traefik/certs/prod/acme.json"
      httpChallenge:
        entryPoint: web

# Production: Secure API without debug
api:
  dashboard: true
  debug: false
  insecure: false

ping:
  entryPoint: "traefik"

# Production: Minimal logging (errors and warnings only)
log:
  level: "WARN"
  filePath: "/var/log/traefik/prod/traefik.log"
  format: "json"

# Production: JSON access logs with minimal fields
accessLog:
  filePath: "/var/log/traefik/prod/access.log"
  format: "json"
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-499"
      - "500-599"