global:
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      tls: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik-public"
    watch: true

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

api:
  dashboard: true
  debug: true
  insecure: true

ping:
  entryPoint: "traefik"

log:
  level: "DEBUG"
  filePath: "/var/log/traefik/dev/traefik.log"
  format: "common"

accessLog:
  filePath: "/var/log/traefik/dev/access.log"
  format: "common"
  bufferingSize: 50
  filters:
    statusCodes:
      - "200-299"
      - "300-399"
      - "400-499"
      - "500-599"
  fields:
    headers:
      defaultMode: "drop"
      names:
        User-Agent: "keep"
        Referer: "keep"
        Accept-Language: "keep"