global:
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      tls: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik-public"
    watch: true

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

api:
  dashboard: true
  debug: false

ping:
  entryPoint: "traefik"

log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"
  format: "common"

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: "common"
  bufferingSize: 100
  filters:
    statusCodes:
      - "200-299"
      - "400-499"
      - "500-599"