global:
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: "letsencrypt"
        domains:
          - main: "example.com"
            sans:
              - "*.example.com"
      middlewares:
        - security-headers@file

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
    network: "traefik-public"
    watch: true
    swarmMode: false
    defaultRule: "Host(`{{ normalize .Name }}.example.com`)"

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "tu-email@example.com"
      storage: "/etc/traefik/certs/prod/acme.json"
      httpChallenge:
        entryPoint: web

api:
  dashboard: true
  debug: false
  insecure: false

log:
  level: "WARN"
  filePath: "/var/log/traefik/prod/traefik.log"
  format: "json"

accessLog:
  filePath: "/var/log/traefik/prod/access.log"
  format: "json"
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-499"
      - "500-599"
    retryAttempts: true
    minDuration: 0
  fields:
    general:
      defaultMode: "drop"
      names:
        ClientAddr: "keep"
        ClientHost: "keep"
        ClientPort: "keep"
        ClientUsername: "keep"
        DownstreamStatus: "keep"
        DownstreamContentSize: "keep"
        Duration: "keep"
        FrontendName: "keep"
        Hostname: "keep"
        Method: "keep"
        Path: "keep"
        Port: "keep"
        Protocol: "keep"
        RequestCount: "keep"
        Timestamp: "keep"
        TraceID: "keep"
    headers:
      defaultMode: "drop"
      names:
        User-Agent: "keep"
        Referer: "keep"
        Accept: "keep"
        Accept-Language: "keep"