# ============================================
# TRAEFIK - CONFIGURACIÓN ESTÁTICA BASE
# ============================================
# Esta configuración es común para dev y prod
# Se sobrescribe con traefik.dev.yml o traefik.prod.yml

global:
  # Deshabilitar telemetría anónima
  sendAnonymousUsage: false

# ============================================
# ENTRYPOINTS (Puntos de entrada)
# ============================================
entryPoints:
  # Puerto 80 - HTTP
  web:
    address: ":80"
    # Configuración para redirección HTTP -> HTTPS
    # NOTA: Esta redirección es GLOBAL en traefik.yml pero se DESACTIVA en traefik.dev.yml
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  # Puerto 443 - HTTPS
  websecure:
    address: ":443"
    # Configuración HTTP/2 y HTTP/3
    http:
      tls: {}

# ============================================
# PROVIDERS (Proveedores de configuración)
# ============================================
providers:
  # Docker provider - detecta contenedores automáticamente
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # Solo expone contenedores con traefik.enable=true
    network: "traefik-public"  # Red por defecto para buscar contenedores
    watch: true  # Monitorea cambios en tiempo real

  # File provider - carga configuración dinámica desde archivos
  file:
    directory: "/etc/traefik/dynamic"
    watch: true  # Recarga automáticamente cuando cambian los archivos

# ============================================
# API y DASHBOARD
# ============================================
api:
  dashboard: true  # Habilita el dashboard web
  debug: false     # Se sobrescribe en dev

# ============================================
# LOGGING
# ============================================
log:
  level: "INFO"  # DEBUG, INFO, WARN, ERROR
  filePath: "/var/log/traefik/traefik.log"
  format: "common"  # common o json

# Log de acceso (peticiones HTTP)
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: "common"
  bufferingSize: 100
  filters:
    statusCodes:
      - "200-299"
      - "400-499"
      - "500-599"