global:
  sendAnonymousUsage: false

# Standard entry points for HTTP/HTTPS
entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      tls: {}

# Docker provider - auto-detects containers with traefik labels
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik-public"
    watch: true

  # Dynamic config files for reloadable configuration
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# API and Dashboard (security depends on environment override)
api:
  dashboard: true

# Health check endpoint
ping:
  entryPoint: "traefik"